### ISSUE TITLE
remove non-functioning "publish" column

### ISSUE THREAD

**Issue by peterstadler** [Edirom/MerMEId#111]
We agreed at todays community meeting to remove non-functioning GUI elements. Since MerMEId 2.0 is focusing on the editing capabilities, we defer the publication workflow and component to a subsequent release.

**Comment by daniel-jettka** [comment]
look in list_files.xq and included files

also remove "Publication status" from filter

**Comment by daniel-jettka** [comment]
Change and view in running MerMEId instance:

* http://localhost:8080/apps/eXide/index.html
* then make changes in files
* then download file into local Git repo and commit
