### ISSUE TITLE
Integrate GitHub repo with Zenodo

### ISSUE THREAD

**Issue by daniel-jettka** [Edirom/MerMEId#113]
Should we integrate the MerMEId repo with Zenodo and automatically publish releases there to have them archived and make them citable via DOI?

-> https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by peterstadler** [comment]
Just flipped the switch:
![Bildschirmfoto 2024-02-15 um 09 51 14](https://github.com/Edirom/MerMEId/assets/2247936/9892a1fc-c349-47c2-8c95-6dd53978e4f9)

Now waiting for the first (proper) release
