### ISSUE TITLE
Data entries not immediately visible after input

### ISSUE THREAD

**Issue by KristinaRichts** [Edirom/MerMEId#134]
When entering source descriptions, the problem occurs that the entered data is not immediately visible and the page must first be exited or reloaded (example NL-DHk).

![PastedGraphic-1](https://user-images.githubusercontent.com/7323877/203523785-4f6bfb92-6fa6-44ae-83fc-17668b5b8b11.jpg)

Entry after B-Bc is not seen:
![PastedGraphic-2](https://user-images.githubusercontent.com/7323877/203524149-1d8e1518-6e6f-4034-9ecb-1f7f502d63fb.jpg)

On the overview page it is displayed:
![PastedGraphic-3](https://user-images.githubusercontent.com/7323877/203524285-7109e561-df21-4df5-ae72-ca02e0f209f7.jpg)

**Comment by peterstadler** [comment]
Couldn't reproduce this here (with Safari and Chrome on Mac). What I tried:
1. add a new row (= a new item) for the Sketch of "Hilsen" (from the samples)
2. click save (the new item will be labeled "no item or label identifier")
3. click "edit" on this item  
4. add some Label on the `details-item.xml` page
5. click "save" on the `details-item.xml` page
6. click "close" to get back to the `edit-source-case.xml` page
7. the page shows the new item with the updated label without being explicitly reloaded

Could this be a local caching issue?

**Comment by daniel-jettka** [comment]
Tried the same in Firefox/Linux Mint, and unfortunately could not reproduce the bug either.

**Comment by KristinaRichts** [comment]
Thank you, @peterstadler and @daniel-jettka ! It turned out that these problems occurred because the input pages were not exited via using the "Close" button. So this issue can be closed.
