### ISSUE TITLE
Missing output of time signature

### ISSUE THREAD

**Issue by KristinaRichts** [Edirom/MerMEId#145]
When recording Telemann's Conclusion from the Musique de table, troisième production, it was noticed that the "crossed out 2" (like the "crossed out c"), which occurs in Telemann's works, is not displayed. Could this time signature be added?

![Bildschirmfoto 2023-01-28 um 00 02 50](https://user-images.githubusercontent.com/7323877/215222680-de8fc0c6-c280-47b6-945f-dfb5bda9e7b7.png)

![Bildschirmfoto 2023-01-28 um 00 02 26](https://user-images.githubusercontent.com/7323877/215222693-67777757-1eb5-42dd-92e4-434199b7e76d.png)

Another example can be found in the Partia G-Dur. The preview shows a black bordered box instead of a c (for 4/4 time) (see screenshot):

![Bildschirmfoto 2023-01-28 um 00 33 16](https://user-images.githubusercontent.com/7323877/215225481-22c1a7d3-02a3-424c-8868-a273fa364db6.png)

![Bildschirmfoto 2023-01-28 um 00 31 42](https://user-images.githubusercontent.com/7323877/215225486-214de516-eb58-4900-9050-678ab3ba4eca.png)

**Comment by peterstadler** [comment]
It looks as if there's currently an (font) issue with rendering musical symbols. These are not displayed properly in the HTML output. 
The other issue with the "crossed out 2" I'll have to check whether and how this might already be supported or how to add this.

**Comment by peterstadler** [comment]
Kleingruppe @dikastes @daniel-jettka and @peterstadler looked at this today and fixed the font issue for symbols selectable within the MerMEId (i.e. common time and cut time).

The other issue should in theory be working as stated in the help: 
> If the pre-defined metres are not sufficient, any other text describing the metre be entered here. MerMEId renders the metre text using a SMuFL font, so musical symbols such as notes or special time signatures may be pasted into this field. 

https://github.com/Edirom/MerMEId/blob/210b08ab000651644cd6db1b48504919516f33e0/forms/includes/meter-input.xml#L42-L46

Will need to investigate further why this is not processed properly.
