### ISSUE TITLE
Subsequent modification of roles of persons

### ISSUE THREAD

**Issue by KristinaRichts** [Edirom/MerMEId#151]
In the Telemann project the problem occurs that the roles of persons in existing records cannot be changed afterwards. In the concrete example, an attempt was made to change the role from "editor" to "author". Even after deleting and recreating the record, the following error message appeared:

![Bildschirmfoto 2023-02-10 um 11 12 31](https://user-images.githubusercontent.com/7323877/218066676-aaba4516-ba52-4171-8e09-270bcc6da550.png)

**Comment by peterstadler** [comment]
Couldn't reproduce the issue with current version v2.0.0-1-g8a8c054c.
@KristinaRichts  Is the issue still occurring on your side?
