### ISSUE TITLE
Time line function does not create output

### ISSUE THREAD

**Issue by halhosar** [Edirom/MerMEId#168]
The time line function adds dates but not comments:

![bilde](https://github.com/Edirom/MerMEId/assets/121748418/c4614d42-8cbe-41b8-9bf2-528cb32009c0)

![bilde](https://github.com/Edirom/MerMEId/assets/121748418/5d4d34f0-f566-4719-aebc-28ba1fb0763c)

I know that an earlier version of MerMEId had a similar problem ca. 2016. It might be worth asking Axel about this.

**Comment by peterstadler** [comment]
Hi @halhosar , I just fixed the timeline display issue, sent in a PR #172 and assigned you as reviewer ;) 
Would be great if you could simply pull the image `edirom/mermeid:issue-168` and test the timeline again!

**Comment by halhosar** [comment]
Hi Peter,

Thank you for this. I shall have a look at it tomorrow.

Halvor
