### ISSUE TITLE
View as XML url is broken again....

### ISSUE THREAD

**Issue by MauPalantir** [Edirom/MerMEId#21]
It yields something like "http://localhost:8080127.0.0.2:8080/apps/mermeid/data/filename.xml" because it formats dcm:server_name then dcm:crud_path which contains the exist_endpoint_seen_from_orbeon variable hard-coded, which would only be correct anyway when you are working on localhost. 

See forms/includes/topmenu.xml for the code.

Proposed solution: introduce a new config variable to the xforms code "external_xml_path" which is server_name/apps/mermeid/data

^ @peterstadler

**Comment by peterstadler** [comment]
might `MERMEID_exist_endpoint` what you're looking for? See https://github.com/Edirom/MerMEId/blob/develop/README.md#mermeid_exist_endpoint

**Comment by peterstadler** [comment]
sorry, this is just the env variable to set `$config:exist-endpoint` in  https://github.com/Edirom/MerMEId/blob/9e5e1d1bab0da69b301415cd0c0a689b40016ab6/modules/config.xqm#L49 

So, within eXist use `$config:exist-endpoint`

**Comment by MauPalantir** [comment]
and what about the Orbeon part?

**Comment by MauPalantir** [comment]
using $exist_endpoint in list_files.xq just points me to servername/data/xmlfile.xml for which exist doesn't display anything but a blank page, it only seems to recognize servername/apps/mermeid/data/xmlfile.xml format. 

in Orbeon, I cannot use just $server_name as well because I would have to get this apps/mermeid(/data/) from somewhere.

**Comment by peterstadler** [comment]
Ok, I think I understand better now …
With the current set of variables it's not possible to have Orbeon reliably present a URL to the client for accessing some file within the data directory.

My proposal would be to add a new variable `$data_collection` to  properties.xml from which we derive all the other currently hardcoded data paths (in config.xqm and mermaid_configuration.xsl). NB, this will affect both internal collection paths and external URL paths but I think they'll map if we assume this `$data_collection` variable to be relative from the app-root.

So (pseudo code):

```
$data_collection = "/data"
$config:data-root := $config:app-root || $data_collection;
<data_collection>
    <xsl:value-of select="$xslt.server-name || $data_collection"/>
</data_collection>
```

Does that make sense?
