### ISSUE TITLE
exist-db 5.3.0-SNAPSHOT does not work anymore with orbeon

### ISSUE THREAD

**Issue by simar0at** [Edirom/MerMEId#22]
Replaced it with 5.2.0 for now. Please check if this has any adverse effects.

**Comment by MauPalantir** [comment]
@simar0at When rebuilding the docker image upon the latest develop branch, the CSS and JS in the resources directory are missing, I don"t see them in existdb. I don't know if this is related, but it seems to ahppen  with the new images that contain this line upon build: 
```Step 22/22 : RUN ["java", "-cp", "/exist/lib/exist.uber.jar", "net.sf.saxon.Transform", "-s:/exist/etc/log4j2.xml", "-xsl:/exist/etc/jetty/webapps/orbeon/WEB-INF/resources/config/log4j2-patch.xsl", "-o:/exist/etc/log4j2.xml"]
 ---> Running in c96ef9318654
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8   -Dsun.jnu.encoding=UTF-8   -Djava.awt.headless=true   -Dorg.exist.db-connection.cacheSize=256M   -Dorg.exist.db-connection.pool.max=20   -Dlog4j.configurationFile=/exist/etc/log4j2.xml   -Dexist.home=/exist   -Dexist.configurationFile=/exist/etc/conf.xml   -Djetty.home=/exist   -Dexist.jetty.config=/exist/etc/jetty/standard.enabled-jetty-configs   -XX:+UnlockExperimentalVMOptions   -XX:+UseCGroupMemoryLimitForHeap   -XX:+UseG1GC   -XX:+UseStringDeduplication   -XX:MaxRAMFraction=1   -XX:+ExitOnOutOfMemoryError
```
![exide](https://user-images.githubusercontent.com/445895/99150802-5c933300-2697-11eb-818c-f8323e8ea8fe.png)

**Comment by MauPalantir** [comment]
@simar0at When rebuilding the docker image upon the latest develop branch, the CSS and JS in the resources directory are missing, I don"t see them in existdb. I don't know if this is related, but it seems to ahppen  with the new images that contain this line upon build: 
```Step 22/22 : RUN ["java", "-cp", "/exist/lib/exist.uber.jar", "net.sf.saxon.Transform", "-s:/exist/etc/log4j2.xml", "-xsl:/exist/etc/jetty/webapps/orbeon/WEB-INF/resources/config/log4j2-patch.xsl", "-o:/exist/etc/log4j2.xml"]
 ---> Running in c96ef9318654
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8   -Dsun.jnu.encoding=UTF-8   -Djava.awt.headless=true   -Dorg.exist.db-connection.cacheSize=256M   -Dorg.exist.db-connection.pool.max=20   -Dlog4j.configurationFile=/exist/etc/log4j2.xml   -Dexist.home=/exist   -Dexist.configurationFile=/exist/etc/conf.xml   -Djetty.home=/exist   -Dexist.jetty.config=/exist/etc/jetty/standard.enabled-jetty-configs   -XX:+UnlockExperimentalVMOptions   -XX:+UseCGroupMemoryLimitForHeap   -XX:+UseG1GC   -XX:+UseStringDeduplication   -XX:MaxRAMFraction=1   -XX:+ExitOnOutOfMemoryError
```

![exide2](https://user-images.githubusercontent.com/445895/99152604-1512a400-26a3-11eb-91aa-4ad1bf0712ca.png)

**Comment by simar0at** [comment]
JAVA_TOOLS_OPTIONS is most likely unrelated.

**Comment by simar0at** [comment]
Works for me. Just looked like there are all JS and CSS missing until I set the endpoint correctly. E. g. 
http://localhost:8081 because I needed to change the port.
![image](https://user-images.githubusercontent.com/641296/99277885-ac583280-282e-11eb-8f9d-fc3359a6f1b8.png)

**Comment by MauPalantir** [comment]
It seems the issue should be something with my local environemnt then, certainly not related to the 5.3 or 5.2 change.
