### ISSUE TITLE
Please check if setting admin password is working.

### ISSUE THREAD

**Issue by simar0at** [Edirom/MerMEId#23]
Just tried to set an admin passwiord using env var
"MERMEID_admin_password": "somepass"
If it works maybe that is just a hickup. Setting mermeid_password did work.

**Comment by peterstadler** [comment]
Just tested with 
```shell
docker run --rm -p 8080:8080 -e MERMEID_exist_endpoint=http://localhost:8080  -e MERMEID_mermeid_password=foobar -e MERMEID_admin_password=blabla  edirom/mermeid:develop
```
and it worked for me 👍

**Comment by simar0at** [comment]
Probably not worth investigating more,
