### ISSUE TITLE
handList doesn't work

### ISSUE THREAD

**Issue by MauPalantir** [Edirom/MerMEId#27]
The input of writer's hands does not work. I think it should be this file: hand-input.xml , which is loaded into item-input.xbl . If there are entries in the xml file, I can see them, but I can't make any changes in the editor. For a new file the button add handList is completely missing

**Comment by peterstadler** [comment]
Hi @MauPalantir , is this still open or fixed by #31 ?

**Comment by daniel-jettka** [comment]
Unfortunately I can't investigate this because I don't yet know and have not come across "input of writer's hands", hand-input.xml or item-input.xbl. 

Any hints anyone?

**Comment by peterstadler** [comment]
I see that the Gade example features `handList` elements. While I was looking for the respective GUI elements I stumbled across several issues with pages not properly loading?!
* editing items from the sources list  (`forms/details-item.xml`)
* adding paper types (sources list -> edit source) at `forms/details-source.xml`

Will add separate issues later …

**Comment by MauPalantir** [comment]
Fixed as #77
