### ISSUE TITLE
 Bug with tinymce in MerMEId

### ISSUE THREAD

**Issue by MauPalantir** [Edirom/MerMEId#28]
TinyMCE widget disappears after the first input, one cannot edit the text after it's saved once.

**Comment by daniel-jettka** [comment]
can confirm this bug for TinyMCE on tab "History"

on tab "Work" this message is thrown after edit in TinyMCE and save action:
`Submission response status: 500 Error type: resource-error URI: http://127.0.0.2:8080/apps/mermeid/data/incipit_demo.xml Headers: DateFri, 11 Jun 2021 13:31:21 GMT `

**Comment by daniel-jettka** [comment]
If anyone has any idea what could cause the disappearance of the TinyMCE box, please let me know ;-)

**Comment by daniel-jettka** [comment]
Trying to reproduce again...

At the moment no bug for these actions:

- for "Incipit Demo" go to "Edit", then tab "History", "Add history note", type "some text", hit "Save file", go back to home, then edit "Incipit Demo" again... TinyMCE still there with the entered content
- for "Maskarade" go to "Edit", then tab "History", add some text to TinyMCE under "History note", hit "Save file", go back to home, then edit "Maskarade" again... TinyMCE still there with the entered content

**Comment by MauPalantir** [comment]
I think this was fixed in #42, closing
