### ISSUE TITLE
invalid values for xml:id

### ISSUE THREAD

**Issue by peterstadler** [Edirom/MerMEId#3]
deployment complains about two files

>  Deployment incomplete, 2 issues found: MEI_attr_list.xml: The XML parser reported a problem: Value of xml:id attribute is not a valid NCName: ; MEI_attr_list_full.xml: The XML parser reported a problem: Value of xml:id attribute is not a valid NCName

In fact, those files have several `xml:id` attributes with empty strings. Without further investigation, it seems as if those were template files which could be dynamically created from a schema/ODD.

**Comment by peterstadler** [comment]
I do not see any complaints anymore in the log files. Has anyone (@simar0at ?) tweaked the logging (for the files still show empty xml:ids)?

**Comment by simar0at** [comment]
Yes I tweaked the log files a bit, but I didn't intend to get rid of these messages.

**Comment by peterstadler** [comment]
error messages seem to be gone, closing here :)
