### ISSUE TITLE
Check external loading protocal

### ISSUE THREAD

**Issue by MauPalantir** [Edirom/MerMEId#36]
On dev/production instance, external JS libraries from HTTPs don't load, esp.
http://www.verovio.org/javascript/latest/verovio-toolkit.js

**Comment by peterstadler** [comment]
@MauPalantir are there more libraries that need to be fixed or was it just Verovio? Can that issue be closed?

**Comment by peterstadler** [comment]
No other problems were reported related to this issue in the last year, so closing
