### ISSUE TITLE
move data directory into dedicated library-package

### ISSUE THREAD

**Issue by dasch124** [Edirom/MerMEId#37]
In order to ease application updates, we should consider moving the data directory out of the application directory into a dedicated library package. On first sight, this only needed adjustment would be in https://github.com/Edirom/MerMEId/blob/develop/modules/config.xqm#L33 + declaring a dependency in expath-pkg.xml – or am I missing something?

**Comment by simar0at** [comment]
I don't think we should have a separate examples file package and a dependency on that. We should just copy or move the example files out of the MerMEId app tree on installing the app if the destination collection is empty. We can then handle the data directory any way we want. Pull it from git or make it a xar-app of its own.

**Comment by claudius108** [comment]
I would vote for having the user data in a Git repository.

One can use the *Tuttle* EXPath app, which adds version control to data collections in eXist-db applications.

Check the [Tuttle EXPath app](http://exist-db.org/exist/apps/public-repo/packages/tuttle?eXist-db-min-version=5.3.0), with a description at [https://faq.teipublisher.com/annotations/git/tuttle/](https://faq.teipublisher.com/annotations/git/tuttle/). The GitHub repo seems to be at [https://github.com/eeditiones/tuttle](https://github.com/eeditiones/tuttle), and the documentation at [https://eeditiones.github.io/tuttle-doc/](https://eeditiones.github.io/tuttle-doc/).
