### ISSUE TITLE
Editing deletes score data

### ISSUE THREAD

**Issue by peterstadler** [Edirom/MerMEId#45]
this is a copy of https://github.com/kb-dk/MerMEId/issues/190 and untested.
Yet we should make doubly sure that this issue is fixed or non-existent!

**Comment by MauPalantir** [comment]
@peterstadler how to test this?

**Comment by peterstadler** [comment]
grab some file with a music section (e.g. from https://github.com/music-encoding/sample-encodings), upload it to the MerMEId, alter it with the MerMEId and see whether the music section survives this process.

**Comment by AnastasiaWawilow** [comment]
We tested, the issue is not fixed.
We used Incipit Demo for the test. We have expanded the music tag in eXide. In MerMEID we have changed the title and saved it. We opened the file again in eXide, we noticed that the music tag is empty.
