### ISSUE TITLE
Update procedure with a permanent exist-db data directory

### ISSUE THREAD

**Issue by simar0at** [Edirom/MerMEId#49]
* Move the example data out of the application source tree on install into a data directory if that does not exist
* Change the controller.xql to look in that (configurable) data directory for the actual xml data and use that to present it as the contents of /data

With this change an update using the regular exist-db application update mechanism (packaged, update) should be possible.
We then only need to provide the xar package either on the common public exist-db package repository or provide such a repository somewhere.

**Comment by peterstadler** [comment]
related to #37 – we should decide whether we want the data to be installable via its own xar package, or via a pre-install hook in the application xar (as proposed by @simar0at here), or even via both methods?

**Comment by simar0at** [comment]
I think it's up to the user to decide how she wants to install the data. I think xar packages is a convenient idea and wie should promote this idea with good examples. But we should not enforce anything.

**Comment by peterstadler** [comment]
Most of the original proposal has been implemented in #59

What's left to do here IMHO?

* create and provide a xar package for every (pre)release. We might update our GitHub actions to automatically create a release for every tag and add the MerMEId xar as a binary there
* add information about deploying/updating the xar to a running eXist-db to the main Readme

**Comment by peterstadler** [comment]
I will update the GitHub actions to build and store a xar package on every run and will try to get this into the eXist Public App Repository

**Comment by simar0at** [comment]
The xar package is a good idea. But the eXist Public App Repository? The package is useless in a default exist-db setup.

**Comment by peterstadler** [comment]
@simar0at what do you mean with "useless"? I think it'd be great to feature the MerMEId in the public app repo. Both for dissemination and for facilitating updates (from a user perspective), especially for people *not* using Docker.
