### ISSUE TITLE
Button "Add main title" without function

### ISSUE THREAD

**Issue by peterstadler** [Edirom/MerMEId#7]
The main title does not show up at all (well, I expected there should be some output of the current title) and clicking the button does not work either.
![Bildschirmfoto 2020-08-13 um 23 30 04](https://user-images.githubusercontent.com/2247936/90189356-51d9b100-ddbd-11ea-8b5b-ebd343481787.png)

**Comment by AnastasiaWawilow** [comment]
we have tested, the issue has been fixed
