### ISSUE TITLE
We want to be MerMEId more friendly to shared (containerized) environment

### ISSUE THREAD

**Issue by simar0at** [Edirom/MerMEId#78]
JVMs are historically not nice about handing back RAM they do not use back to the OS. All garbage collectors up to and including G1GC used in the standard exist-db 5.x container distribution only rarely release RAM if at all.

If we run MerMEId on containerized servers or kubernetes setup together with numerous other services RAM is shared and on average the RAM consumption should be as low as possible.

In recent years a new GC was created: [Shenandoah GC](https://wiki.openjdk.java.net/display/shenandoah/Main) This GC has some other benefits but also it is very good at releasing RAM back to the OS in a timely manner (a few seconds after it is freed internally)

There problems with this approach:
The official existdb/existdb container(s) are based on an openjdk 1.8.0 distribution which does not support Shenandoah GC. Shenandoah GC is supported in the openjdk-1.8.0 distribution only in EPEL/RHEL/CentOS based distributions.

The base container of the official existdb distribution is available with openjdk 11 and this version of openjdk (almost always) supports the Shenandoah GC

To be nice to shared environments we need to use a derived version of existb and someone has maintain that until maybe the official existdb moves to openjdk 11.

The ACDH-CH has to maintain a container friendly copy of existdb anyway so [this version of existdb exists](https://hub.docker.com/r/acdhch/existdb).

**Comment by peterstadler** [comment]
Hi @simar0at, this sounds like a great improvement, still I have some questions:
* this does not seem like a genuin MerMEId, but rather an eXist issue. Have you approached them already because many other projects might benefit from this improvement?
* I believe your `acdhch/existdb` image is fine yet I cannot find the proper Dockerfile for it to check. Having this available as well as a transparent build pipeline would be much appreciated.

**Comment by simar0at** [comment]
The Dockerfile and everything else to build this is here: https://github.com/acdh-oeaw/exist/blob/5.2.0-java11-ShenGC/exist-docker/src/main/resources-filtered/Dockerfile
I actually have not tried 5.3.0 again after we had errors with one of the snapshot builds. The existdb people never updated their image of 5.2.0 after release more than a year ago and I think this was deliberate.
I am hesitant to approach existdb. I have not had fruitful exchanges with them.
So also I am looking for some known working setups before I suggest anything to the people upstream.

**Comment by peterstadler** [comment]
For the record, see the minutes of the Community Meeting from 2021-09-06: https://github.com/Edirom/MerMEId/wiki/2021-09-06-MerMEId-Community-Call-%238#pr-79-be-more-nice-in-shared-hosting
